### ISSUE TITLE
Issue with Load and Save Buttons

### ISSUE THREAD

**Issue by corymyslywec** [Photonsters/FileMerger#3]
Hello,

The Load and Save buttons for this do not work for me in Windows 10.   Running Python 3.7.4

I've attached the error I am getting from the command prompt

![filemerger-error](https://user-images.githubusercontent.com/56360063/66500368-63607700-ea8f-11e9-8965-2d7f1eb2b71c.PNG)

**Comment by NardJ** [comment]
Thx, should be fixed now (Did test on Win10 64 bit and Linux Mint 64 bit)

Op wo 9 okt. 2019 om 18:22 schreef HankHillPropane <notifications@github.com
